package ak.main.Ontology.Constants;

public enum MachineResponse {
    ALUMINIUM_LEVEL_LOW,
    CAR_BODY_BOX_CAPACITY_EMPTY,
    CAR_BODY_BOX_CAPACITY_FULL,
    CAR_INTERIOR_CHASSIS_BOX_CAPACITY_EMPTY,
    CAR_INTERIOR_CHASSIS_BOX_CAPACITY_FULL,
    CAR_WHEEL_BOX_CAPACITY_EMPTY,
    CAR_WHEEL_BOX_CAPACITY_FULL,
    LOW_FURNACE_TEMP,
    MALFUNCTIONING_PRESS,
    NO_ALUMINIUM,
    NO_PAINT,
    NO_PLASTIC,
    PACKAGING_MATERIAL_EMPTY,
    PACKAGING_MATERIAL_LOW,
    PAINT_LEVEL_LOW,
    PAINT_NOZZLE_BLOCKED,
    PLASTIC_LEVEL_LOW,
    SERVO_MALFUNCTION,
    PACKAGING_JAM}
